[server]
headless = true
enableCORS = false
port = 8501

headless = true

[theme]
primaryColor = "#4CAF50"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[general]
# Tell Streamlit Cloud where to find your app's main file
# Path is relative to the root of your GitHub repo
target = "app/main.py"
